
create table tb_users (date_creation timestamp(6) not null, last_login timestamp(6), user_id bigint generated by default as identity, email varchar(255) not null unique, name varchar(255) not null, password varchar(255) not null, phone varchar(255), primary key (user_id));
create table tb_restaurants (average_rating float4 not null check ((average_rating>=0) and (average_rating<=5)), quantity_evaluations integer not null check (quantity_evaluations>=0), total_evaluations integer not null check (total_evaluations>=0), date_creation timestamp(6) not null, last_login timestamp(6), restaurant_id bigint generated by default as identity, cnpj varchar(14) not null unique, phone varchar(15) not null, email varchar(100) not null unique, fantasy varchar(100) not null, category varchar(255) check (category in ('RESTAURANTE','PADARIA','SUPERMERCADO','CAFETERIA','PASTELARIA','SUSHI_BAR','FAST_FOOD','LANCHONETE','ACOUGUE','EMPORIO','PEIXARIA','CHURRASCARIA','CONFEITARIA','HORTIFRUTI','PIZZARIA','OUTROS')), description varchar(255), password varchar(255) not null, url_banner varchar(255), url_logo varchar(255), primary key (restaurant_id));
create table tb_products (active boolean not null, original_price float4 not null, quantity integer not null, sell_price float4 not null, addition_date timestamp(6) not null, expiration_date timestamp(6) not null, product_id bigint generated by default as identity, restaurant_id bigint not null, category varchar(255) not null check (category in ('DOCE','SALGADO','MISTO')), description_product varchar(255), name_product varchar(255) not null, url_img_product varchar(255), primary key (product_id));

CREATE TYPE delivery_type AS ENUM ('RETIRADA', 'ENTREGA');
create table tb_orders (
    total_value float4 not null,
    address_id bigint not null,
    delivery_date timestamp(6),
    order_date timestamp(6) not null,
    order_id bigint generated by default as identity,
    restaurant_id bigint not null,
    review_id bigint unique,
    transaction_id bigint unique,
    user_id bigint not null,
    delivery_type delivery_type default 'RETIRADA' not null,
    order_status varchar(255) not null check (order_status in ('PENDENTE', 'PREPARANDO', 'AGUARDANDO_RETIRADA', 'CONCLUIDO', 'CANCELADO')),
    primary key (order_id)
);

create table tb_addresses (is_standard boolean not null, state varchar(2) not null, address_id bigint generated by default as identity, restaurant_id bigint, user_id bigint, address_type varchar(255) not null check (address_type in ('USER','RESTAURANT','ORDER')), cep varchar(255) not null, city varchar(255) not null, complement varchar(255), district varchar(255) not null, number varchar(255) not null, street varchar(255) not null, type varchar(255) not null, primary key (address_id));
create table tb_cards (cvv varchar(3) not null, card_id bigint generated by default as identity, user_id bigint, holder_name varchar(100) not null, cpf varchar(255) not null, number varchar(255) not null, validity varchar(255) not null, primary key (card_id));
create table tb_cart (total_value float4 not null check (total_value>=0), cart_id bigint generated by default as identity, user_id bigint not null, primary key (cart_id));
create table tb_cart_items (quantity integer not null check (quantity>=1), subtotal float4 not null, unit_value float4 not null, added_at timestamp(6) not null, cart_id bigint not null, product_id bigint not null, restaurant_id bigint, primary key (cart_id, product_id));
create table tb_contacts (contact_id bigint generated by default as identity, restaurant_id bigint not null, phone varchar(15) not null, description varchar(255) not null, primary key (contact_id));
create table tb_favorites (favorite_id bigint generated by default as identity, restaurant_id bigint not null, user_id bigint not null, primary key (favorite_id));
create table tb_historical_orders (date_mod timestamp(6) not null, historical_order_id bigint generated by default as identity, order_id bigint not null unique, restaurant_id bigint not null, user_id bigint not null, order_status varchar(255) not null check (order_status in ('PENDENTE','PREPARANDO','AGUARDANDO_RETIRADA','CONCLUIDO','CANCELADO')), primary key (historical_order_id));
create table tb_notifications (msg_read boolean not null, notification_id bigint generated by default as identity, restaurant_id bigint not null, send_date timestamp(6) not null, user_id bigint not null, msg_notification varchar(255) not null, primary key (notification_id));
create table tb_order_items (quantity integer not null, subtotal float4 not null, unit_value float4 not null, order_id bigint not null, product_id bigint not null, primary key (order_id, product_id));
create table tb_restaurant_hours (hours_id bigint generated by default as identity, restaurant_id bigint not null, closing_time varchar(255) not null, day_of_week varchar(255) not null check (day_of_week in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')), opening_time varchar(255) not null, primary key (hours_id));
create table tb_reviews (rating_note integer not null check ((rating_note>=1) and (rating_note<=5)), order_id bigint unique, rating_date timestamp(6) not null, restaurant_id bigint not null, review_id bigint generated by default as identity, user_id bigint not null, rating_comment varchar(500), primary key (review_id));
create table tb_transactions (transaction_value numeric(38,2) not null, card_id bigint not null, order_id bigint not null unique, transaction_date timestamp(6) not null, transaction_id bigint generated by default as identity, transaction_status varchar(255) not null check (transaction_status in ('APROVADA','NEGADA','PENDENTE')), primary key (transaction_id));
alter table if exists tb_addresses add constraint FKaadu8lkilm76bx8tj6a0s6m2l foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_addresses add constraint FK6w37kk7q0gqtrp2pg965khe6l foreign key (user_id) references tb_users;
alter table if exists tb_cards add constraint FK2dhdhd80ro32i6w7iwxnh8ndc foreign key (user_id) references tb_users;
alter table if exists tb_cart add constraint FK2plvrqp3ei6slwg8ol97xc5ns foreign key (user_id) references tb_users;
alter table if exists tb_cart_items add constraint FKa7scce3udf66o87j267gfotlf foreign key (cart_id) references tb_cart;
alter table if exists tb_cart_items add constraint FK3afurtmusv7pceugwewpv5ldh foreign key (product_id) references tb_products;
alter table if exists tb_cart_items add constraint FKl32y8b7fji6ospsajjlhf1frw foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_contacts add constraint FKkskbs59uc5vdrdqkdkj7au84a foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_favorites add constraint FKr2xcdck97dul44olay1fxauqo foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_favorites add constraint FK16hcd8t2s6ftqn5jgawr3btch foreign key (user_id) references tb_users;
alter table if exists tb_historical_orders add constraint FK24q18htsy8t1emq3urbe5savg foreign key (order_id) references tb_orders;
alter table if exists tb_historical_orders add constraint FK762em5xdb3ja4fpohjjav4j5t foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_historical_orders add constraint FK1fqypcxmv9sj1ghcqugq4k8tr foreign key (user_id) references tb_users;
alter table if exists tb_notifications add constraint FK4xoj9n4bkfma4u343va65em08 foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_notifications add constraint FKo23w9cpi6nqcusd6u7vmbf3qw foreign key (user_id) references tb_users;
alter table if exists tb_order_items add constraint FKr9uuphipacrs0n0qi7vyxba4q foreign key (order_id) references tb_orders;
alter table if exists tb_order_items add constraint FKsfeg5hsfxv6v5vlcham57bibu foreign key (product_id) references tb_products;
alter table if exists tb_orders add constraint FKk531vffddjav0so73efnvv95q foreign key (address_id) references tb_addresses;
alter table if exists tb_orders add constraint FKpv1iemgm1p09hodqlowox3o12 foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_orders add constraint FKomxe2pe2xvc3oui9u5a83yoax foreign key (review_id) references tb_reviews;
alter table if exists tb_orders add constraint FKpt0pn9s3rdy7rt1qh83y2ury1 foreign key (transaction_id) references tb_transactions;
alter table if exists tb_orders add constraint FKgprqgp552scklsm3rk6uyvh foreign key (user_id) references tb_users;
alter table if exists tb_products add constraint FKi3c1588geefrqkdt47vstj6is foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_restaurant_hours add constraint FKl1t1s600ck1u0xb34rfq9kyu8 foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_reviews add constraint FKn7gyk85gvyvte4b4jlmkwiyex foreign key (order_id) references tb_orders;
alter table if exists tb_reviews add constraint FK4vqh7ayh79icanqmyo48qom6e foreign key (restaurant_id) references tb_restaurants;
alter table if exists tb_reviews add constraint FKb9mp1nas3nijau8h3hmtejt5o foreign key (user_id) references tb_users;
alter table if exists tb_transactions add constraint FKlttwrktfn5eevl4vr4w4cehiv foreign key (order_id) references tb_orders;
